---
- hosts: vm_centos
  remote_user: root
  become: yes
  gather_facts: no

  tasks:
  - name: Apache latest version installation
    yum:
      name: httpd
      state: latest

  # - name: Remove Apache
  #   yum:
  #     name: httpd
  #     autoremove: yes
  #     state: absent

  - name: Enable service to start on boot up
    service:
      name: httpd
      state: started
    notify: Restart apache service

  handlers:
  - name: Restart apache service
    service:
      name: httpd
      state: restarted
      