---
- hosts: vm_windows
  tasks:
    - name: Print message
      debug:
        msg: Hello Ansible on Windows VM

    - name: Installing some programs
      win_chocolatey:
        name: "{{ item }}"
        state: reinstalled
      with_items:
        - git.install
        - firefox