---
- hosts: vm_windows
  tasks:

    - name: Install Apache
      win_chocolatey:
        name: apache-httpd
        state: latest

    - name: Remove Apache
      win_chocolatey:
        name: apache-httpd
        state: absent
    